import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Background from "@/component/Background";
import { SignupFormDemo } from "@/component/Signup";
import { TypewriterEffectSmoothDemo } from "@/component/Typewriter";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <TypewriterEffectSmoothDemo/>
        <SignupFormDemo/>
        <Background/>
        
        {children}</body>
    </html>
  );
}
